name: Homebrew Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: gobackup
          homebrew-tap: itgcloud/homebrew-tap
        env:
          COMMITTER_TOKEN: ${{ secrets.RELEASE_TOKEN }}
