name: Build & Test
on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GO_ENV: test
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v5.3.1

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
        id: go

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test ./...
